###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "le huu tam 234 567 89",
    "password": "Tamleasdsadacxs"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
     "username": "le huu tam 234 567 89",
    "password": "Tamleasdsadacxs"
}