###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "jim22",
  "password": "jim22"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "jim22",
  "password": "jim22"
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NGEyYmUyMTNjMDI0Mzk5N2Y4MWIwOGEiLCJpYXQiOjE2ODgzODg1MDN9.LDXI_Kd0AMg6nHzUMBsiVngfvcNsdaTqvUol3B8jyt0

{
  "title": "React",
  "description": "React",
  "url": "react.com",
  "status": "TO LEARN"
}



